name: Continous Integration
on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [12, 14, 16]
    # services:
    #   mysql:
    #     image: mysql:5.7
    #     env:
    #       MYSQL_USER: root
    #       MYSQL_PASSWORD: root
    #       MYSQL_ALLOW_EMPTY_PASSWORD: yes
    #       MYSQL_DATABASE: testdb
    #       MYSQL_ROOT_PASSWORD: password
    #       MYSQL_HOST: localhost
    #     ports:
    #       - 3306
    #     options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 # -v /usr/bin/docker/mysql:/var/run/mysqld/mysqld.sock
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          apt-get update && apt-get install -y mysql-client
          sudo /etc/init.d/mysql start
      - run: npm install
      - run: npm test
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          CI: true
  code-lint:
    name: Code Lint
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Bootstrap project
        run: |
          npm ci --ignore-scripts
      - name: Verify code linting
        run: npm run lint

  commit-lint:
    name: Commit Lint
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Bootstrap project
        run: |
          npm ci --ignore-scripts
      - name: Verify commit linting
        run: npx commitlint --from origin/master --to HEAD --verbose